[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Example: add libraries here, e.g. meshtastic, LoRa, DHT, BME280
; lib_deps = meshtastic/Meshtastic@^1.0.0, adafruit/DHT sensor library@^1.4.0

build_flags = -DCORE_DEBUG_LEVEL=5

; You can add additional envs for other boards (eg. lora module boards)

[platformio]
default_envs = esp32dev